In [1]:
import pandas as pd

In [2]:
# Series
s = pd.Series([6, 7, 8, 9, 10])
print(s)
print(type(s))

# index - based access
print(s[0])
print(s[3])

print(s.index)

0     6
1     7
2     8
3     9
4    10
dtype: int64
<class 'pandas.Series'>
6
9
RangeIndex(start=0, stop=5, step=1)

In [3]:
s = pd.Series([23, 24, 25, 26, "ABC"], index=["Adam", "Eve", "Bob", "Charlie", 30])
print(s)
print(type(s))

# label - based access
print(s["Adam"])
print(s["Charlie"])

print(s.index)

Adam        23
Eve         24
Bob         25
Charlie     26
30         ABC
dtype: object
<class 'pandas.Series'>
23
26
Index(['Adam', 'Eve', 'Bob', 'Charlie', 30], dtype='object')

In [4]:
# Vectorization
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])

print(s1 + s2)

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [5]:
# DataFrame
info = {
    "Name": ["Avishek", "Rahul", "Tanmay"],
    "Age": [23, 24, 25],
    "GPA": [9.5, 8.6, 7.2]
}

df = pd.DataFrame(info)
print(df)
print(type(df))

print(df.index)
print(df.columns)

      Name  Age  GPA
0  Avishek   23  9.5
1    Rahul   24  8.6
2   Tanmay   25  7.2
<class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='str')

In [6]:
df

      Name  Age  GPA
0  Avishek   23  9.5
1    Rahul   24  8.6
2   Tanmay   25  7.2

In [7]:
df = pd.DataFrame([["Avishek", 23], ["Rahul", 24], ["Tanmay", 25]], columns=["Name", "Age"])

print(df)

      Name  Age
0  Avishek   23
1    Rahul   24
2   Tanmay   25

In [8]:
import numpy as np

np_arr = np.array([[1, 2, 3], [4, 5, 6]])

df = pd.DataFrame(np_arr, columns=["A", "B", "C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [9]:
# Read CSV data
df = pd.read_csv("Employee_data.csv")
print(df)
print(type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
<class 'pandas.DataFrame'>

In [10]:
# Read JSON data
df = pd.read_json("Employee_data.json")
print(df)
print(type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
<class 'pandas.DataFrame'>

In [11]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [12]:
# DataFrame Methods
print(df.head(4))       # starting 4 rows
print()
print(df.tail(3))       # ending 3 rows
print()
print(df.sample(2))     # random 2 rows
print()
print(df.info())        # info about data
print()
print(df.shape)         # (10, 5) -> (row, column)
print()
print(df.describe())    # describes the numerical columns
print()
print(df.columns)       # prints columns
print()
print(df.nunique())     # prints number of unique rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000

   ID    Name  Age Department  Salary
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

   ID   Name  Age Department  Salary
3   4  David   45  Marketing   91000
6   7  Grace   41         HR   82000

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 628.0 bytes
None

(10, 5)

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='str')

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64